### ISSUE TITLE
bug(Global): User is stuck on chat pages after entering a chat

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/UplinkWeb#111]
**Issue:**
When you add someone and go to start a chat with them, once you are on the chat page you will be stuck there and not able to navigate to any other page

**Screen recording:**

https://github.com/Satellite-im/UplinkWeb/assets/93608357/efd6d865-70f7-4de7-927c-a00215edb462

**Comment by InfamousVague** [comment]
Should be resolved.
