### ISSUE TITLE
bug(profile): Some pictures arent working with Profile Pic/Banner

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/UplinkWeb#136]
**Issue:**
Sometimes when you try to upload a profile picture or Banner picture nothing will happen. Ive noticed it mostly with jpegs but it seems to be pretty random 

**Screen recording:**

https://github.com/Satellite-im/UplinkWeb/assets/93608357/0d0ef4ce-4973-438d-a031-5afc4e286d9c

**Photos that didnt work:**

![photo2](https://github.com/Satellite-im/UplinkWeb/assets/93608357/26cd0ebf-4aa9-47ea-8e22-a0df63c6a9da)
![photo3](https://github.com/Satellite-im/UplinkWeb/assets/93608357/202a4a80-36a0-469c-b6db-b009923f4649)
![photo8](https://github.com/Satellite-im/UplinkWeb/assets/93608357/35854fe8-9e5f-4674-abe3-ba3153a87132)

**Comment by luisecm** [comment]
Cypress tests for uploading banner or profile picture are randomly failing. It looks like a bug was recently introduced but its flaky
