### ISSUE TITLE
bug(chat): Text renders outside of the textbox 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/UplinkWeb#141]
**Issue:**
If you start to type a long message in chat, the text will eventually start rendering outside of the textbox area 

**Screenshot:**
<img width="867" alt="Screenshot 2024-06-26 at 3 50 25 PM" src="https://github.com/Satellite-im/UplinkWeb/assets/93608357/800fa450-f444-4d56-b698-17a8cca7d556">

**Comment by luisecm** [comment]
@phillsatellite @stavares843 @Flemmli97 When testing this PR #186 I noticed that the same error happens with chat messages, but I believe we will need a new ticket for this:

![image](https://github.com/Satellite-im/UplinkWeb/assets/35935591/d86bec22-1345-407d-902f-4b0155ddf6bb)
