### ISSUE TITLE
bug(Profile): HEIC images do not work 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/UplinkWeb#204]
**Issue:**
Like the title says most heic images are not working when you try to upload them as a profile picture. This might be important down the road as we plan to release on mobile and most of the US are iPhone users 

**Screen recording:**

https://github.com/Satellite-im/UplinkWeb/assets/93608357/c335a914-e0e1-43cf-99a2-2085ca26e2ac

**Comment by dariusc93** [comment]
In this case, it might be best to convert the image to jpg or png before passing it over to warp. The library used to for processing the image doesnt support heic so this would probably need to be converted on the frontend to something that is supported (which commonly is jpg or png).
