### ISSUE TITLE
bug(Status): Online Status will not change until friend navs to different page and back 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/UplinkWeb#229]
**Issue:**
If one of your friends updates their online status, it will not appear for you until you nav to a different page and back again. 

Messages in chats also do not update at all. Any new message you send will have the current correct online status but any message you sent prior will not update at all 

Online Status in sidebar does not update at all 

**Screen recording:**

https://github.com/Satellite-im/UplinkWeb/assets/93608357/20ceafca-0c37-4ee5-914f-2a2911f1643a

**Comment by luisecm** [comment]
This should be solved by this PR #238
