### ISSUE TITLE
bug(Chats): Unsent messages persist through multiple chats 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/UplinkWeb#251]
**Issue:**
If you are in a chat with UserA and you have any unsent messages and you then navigate to different chats the unsent messages from the UserA chat will still be displayed 

**Screen recording:**

https://github.com/user-attachments/assets/b238609e-89f4-48e7-9866-d56ef036abea

**Comment by Flemmli97** [comment]
there is a possiblity that this is fixed in #261 as ive changed some subscription stuff there too
