### ISSUE TITLE
bug(Error): Error: RayGun extension is unavailable

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/UplinkWeb#288]
**Issue:**
After typing in a PIN on account creation this error appears in console `Uncaught (in promise) Error: RayGun extension is unavailable`

**Steps to reproduce:**
- Simply follow through the account creation flow and after you create a pin and proceed to the next page the error will appear 

**Screenshot:**
<img width="853" alt="Screenshot 2024-07-18 at 3 59 06 PM" src="https://github.com/user-attachments/assets/ca2cd1f9-c7a1-4462-b28a-f4139d1add71">

**Comment by dariusc93** [comment]
is this consistent or just at random?

**Comment by dariusc93** [comment]
Then its likely that a raygun functions are being called instantly before awaiting for the account to initialized or be created.

**Comment by Flemmli97** [comment]
#272 is working on that problem too
