### ISSUE TITLE
bug(Login): Black screen after entering account

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/UplinkWeb#289]
**Issue:**
Sometimes when trying to enter your account you will enter your pin and it will load into a black screen. I've noticed that if you arrive at the black screen and you click the refresh button once the normal ui will appear but you will be stuck on the chat page. This bug can be random at times though so reproducing might take a few attempts.

These errors in console appear when this bug happens

`Uncaught Error: recursive use of an object detected which would lead to unsafe aliasing in rust`

`[HMR][Svelte] Unrecoverable HMR error in <+page>: next update will trigger a full reload`

`Uncaught (in promise) Error: derived() expects stores as input, got a falsy value`
    
`warp_ipfs.js?v=6d0eea24:5533 Uncaught Error: closure invoked recursively or after being dropped`
    
**Steps to reproduce:**
- Simply try to login or create an account (Ive found that this happens more often when trying to log back into an account)

**Screenshot:**
<img width="857" alt="Screenshot 2024-07-18 at 4 17 40 PM" src="https://github.com/user-attachments/assets/8308566c-fe55-4b56-82d8-ccddda5d07a5">

**Comment by Flemmli97** [comment]
did you test after https://github.com/Satellite-im/UplinkWeb/commit/84f5a11e78fc309ac92b9106d16630117fd18d24 though?
