### ISSUE TITLE
feat(Pay): Improve UI for payment request (chat message)

### ISSUE THREAD

**Issue by ashneverdawn** [Satellite-im/UplinkWeb#327]
We should improve the appearance of the chat message containing the payment request. 

Currently it looks like this:
<img width="459" alt="Screenshot 2024-07-31 at 8 19 41 AM" src="https://github.com/user-attachments/assets/cd43685a-8999-48d9-a246-b6818eea94a1">

**Comment by XileHorizon** [comment]
Ongoing design flows for payment UI: https://www.figma.com/design/IVesRs0flNgvvx09EG0VYk/Payments?node-id=0-1&t=IozLwszmYL2boTuY-0
