### ISSUE TITLE
bug(firefox): On Friends page - minimum length of 13 chars error is shown after pasting valid did key

### ISSUE THREAD

**Issue by luisecm** [Satellite-im/UplinkWeb#367]
1. Create two accounts - at least one in Firefox
2.On the firefox client, go to Friends page
3. On firefox client, paste a valid did:key from the remote user in Add Someone Input
4. You will see that minimum length is 13 characters error message is displayed after pasting the valid did key, even though the text pasted has more than 13 characters
5. This error is not happening on Chrome/Brave

![image](https://github.com/user-attachments/assets/361d5e87-a691-42fa-a90f-694ed8676fc0)

**Comment by stavares843** [comment]
seems this is happening with any input field on firefox

firefox

<img width="753" alt="Captura de ecrã 2024-08-07, às 12 21 15" src="https://github.com/user-attachments/assets/da1ce384-ee5a-40eb-8690-e6d074c1db95">

chrome

<img width="792" alt="Captura de ecrã 2024-08-07, às 12 21 19" src="https://github.com/user-attachments/assets/3313dc73-2dc4-4b8d-a90b-28d5899ded74">

**Comment by stavares843** [comment]
i added some logs to debug and i noticed when we add 4 chars firefox only gets 3 

<img width="1049" alt="Captura de ecrã 2024-08-07, às 12 23 22" src="https://github.com/user-attachments/assets/9bb086ca-c471-4e93-aa3b-9561d151001c">


if we add 5 he gets 4 and the error disappears

<img width="1107" alt="Captura de ecrã 2024-08-07, às 12 23 28" src="https://github.com/user-attachments/assets/50a8177e-e947-492d-ab02-0401e7b45b82">

**Comment by stavares843** [comment]
fixed here
https://github.com/Satellite-im/UplinkWeb/pull/368
