### ISSUE TITLE
bug(chat): Typing in chat throws error 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/UplinkWeb#373]
**Issue:**
Whenever the user clicks into the chatbar and starts to type this error message appears in console on each press of a key 

**Screenshot:**
<img width="856" alt="Screenshot 2024-08-07 at 1 23 30 PM" src="https://github.com/user-attachments/assets/e8d12711-1a88-4f6b-a1e1-3b737c76cd66">

**Comment by Flemmli97** [comment]
should be resolved now by #402
