### ISSUE TITLE
bug(chat): Missing message if enter key is used to send 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/UplinkWeb#374]
**Issue:**
When in a chat if you use the enter key to send a message the message will not be sent. You will also be thrown these errors in the console 

**Screenshot/recording:**
<img width="859" alt="Screenshot 2024-08-07 at 1 28 37 PM" src="https://github.com/user-attachments/assets/fc730541-e7a6-4d2a-8576-638f765f7c49">

https://github.com/user-attachments/assets/9dd3832b-ef67-4ffd-9363-fe9f968955b5

**Comment by stavares843** [comment]
added on the pr
