### ISSUE TITLE
bug(global): Clicking send button breaks chats 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/UplinkWeb#375]
**Issue:**
Were working through trying to debug what is the cause of this. We will add more to the ticket as we find out more today. It seems like clicking the send button in chat breaks a lot on the app. 

What we've noticed so far is if the user clicks the send button at some point it will stop working. and you will get this error

`Uncaught Error: recursive use of an object detected which would lead to unsafe aliasing in rust`

When this happens a lot of buttons break in the app, the user cannot add a friend, cannot remove a friend, cannot block a friend, cannot upload a file, cannot upload a profile picture. 

https://github.com/user-attachments/assets/8b1f2bea-df93-4d73-a763-baf4832e38ae

**Comment by stavares843** [comment]
added on the pr
