### ISSUE TITLE
bug(Settings): Add/Cancel buttons render outside of wallet modal

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/UplinkWeb#377]
**Issue:**
When you are adding a wallet to your account the Add and Cancel buttons render outside of the box when not in fullscreen

**Screenshot:**
<img width="516" alt="Screenshot 2024-08-07 at 2 18 27 PM" src="https://github.com/user-attachments/assets/b16f9795-3987-40f6-ba1f-ac09371f027d">

**Comment by stavares843** [comment]
seems no longer happens
