### ISSUE TITLE
bug(Global): Account endlessly loads

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/UplinkWeb#423]
**Issue:**
Something happened yesterday to my Chrome and Brave account (normal browser not incognito) I was switching branches and then when I tried to load my account it just endlessly loads a spinner. Theres an error that gets thrown in console (pic shown below) Ive tried clearing my storage multiple times but that doesnt seem to fix it 

This is only when I run `npm run dev` though if I run `npm run build` / `npm run preview` account loads in fine

**Screenshot:**
![image](https://github.com/user-attachments/assets/37dbcb72-b947-49ea-9c87-443b65d916fd)

<img width="1294" alt="Screenshot 2024-08-16 at 12 36 26 PM" src="https://github.com/user-attachments/assets/96b880a2-15f0-491e-ab44-34c7e76757f6">
<img width="860" alt="Screenshot 2024-08-16 at 12 33 59 PM" src="https://github.com/user-attachments/assets/75cc2fac-5b62-4fbe-9019-91f706347fde">

**Comment by Flemmli97** [comment]
is this still a problem?
