### ISSUE TITLE
feat(Chat): Show true size of pictures when previewing file

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/UplinkWeb#426]
**Issue:**
When you preview pictures that were sent in chat its the same fixed size for each one. Instead we should show the true size like how we had it in native Uplink

**Screen recording:**

https://github.com/user-attachments/assets/9ddebaf8-d60e-4c08-8bc5-4b2b3af7ac3a

**Comment by Flemmli97** [comment]
just a note but native uplink also doesnt show the true size. it still only shows the thumbnail. reason why its bigger there is cause the thumbnail size config is set to be bigger
