### ISSUE TITLE
bug(Friends): Friend request is not appearing 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/UplinkWeb#438]
**Issue:**
There seems to be something up with friending. If I send a request from User A to User B, User B will get a toast notification saying that they got a friend request. When they go to the Active page nothing is there. On User A side if you go to active requests nothing will appear under pending 

**Screen recording:**

https://github.com/user-attachments/assets/5813059d-eea7-4796-bd31-a73e1ebd1b11

**Comment by tooshel** [comment]
happens for me too Phill! Brand new accounts. Canary and Chromium with all browser data cleared.
