### ISSUE TITLE
bug(chat): Duplicate messages after removing/re-adding friend 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/UplinkWeb#480]
**Issue:**
When you remove a friend and re-add them and start another chat whatever message you send it will send a duplicate 

**Steps to reproduce:**
- Add a friend
- Start a chat (Do not send any message)
- Remove friend 
- Re-add friend 
- Start another chat 
- Now any message you send will send duplicates 

**Screenshot / recording:**
<img width="447" alt="Screenshot 2024-08-28 at 12 28 04 PM" src="https://github.com/user-attachments/assets/76086d28-4d78-4984-9d97-7b18fb2e19fd">

https://github.com/user-attachments/assets/c5cdaa32-afd3-4d3f-91cd-3095c939d075

**Comment by stavares843** [comment]
also happens here
