### ISSUE TITLE
bug(Groups): Cant close GroupMembers on 2nd attempt on opening 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/UplinkWeb#499]
**Issue:**
When you open up Group Members for the 2nd time, it will not close 

**STR:**
Open GroupMembers 
Close 
Open again 
Cant close 

**Screen recording:**

https://github.com/user-attachments/assets/8caa0ace-4986-43cb-a397-260088d50a73

**Comment by stavares843** [comment]
also happens here
