### ISSUE TITLE
bug(files): delete folders option does not work

### ISSUE THREAD

**Issue by luisecm** [Satellite-im/UplinkWeb#517]
1. Create an account
2. Go to Files
3. Create a new folder
4. Now, right click on the same folder created to open context menu
5. Select "Delete" 

Expected Result: Folder should be deleted
Actual Result: Folder is not deleted

https://github.com/user-attachments/assets/81f418f0-dede-4fcd-adb4-d040b339ca56

**Comment by stavares843** [comment]
fixed here

https://github.com/Satellite-im/UplinkWeb/pull/487
