### ISSUE TITLE
implement(chats): convert to emoji is not working when is enabled

### ISSUE THREAD

**Issue by luisecm** [Satellite-im/UplinkWeb#528]
1. Create an account
2. Add any friend
3. Go to settings - messages
4. On Settings Messages, enable - Convert to Emoji feature
5. Start a conversation and type in chatbar input "<3" 

Expected Result: Texts like <3 should be converted to emoji (heart in this example) when Convert to Emoji is enabled

Actual Result: Texts like <3 are not converted to emoji (heart in this example) when Convert to Emoji is enabled

**Comment by stavares843** [comment]
also happens here
