### ISSUE TITLE
task(Chat): Wire up Share Files

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/UplinkWeb#567]
**Issue:**
When you send a message in chat there is a Share button that doesnt seem to be hooked up yet. Luis and I are thinking this is for sharing said file with other friends on Uplink. If so then when clicked a list of friends should pop up and user should be able to select multiple friends from that list and send file to 

**Screenshot:**
![image](https://github.com/user-attachments/assets/b6a9a3c4-88b4-4c9e-8b3f-f92d98f81487)

**Comment by Jekrimo** [comment]
Hey @phillsatellite ! I was just lookin at this one and seems the share and add to file button seem to be hidden already?
