### ISSUE TITLE
bug(FIles): Go Back button stopped working 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/UplinkWeb#568]
**Issue:**
It looks like when you go into the subfolders in chat_media and try to use the Go Back button it doesnt work 

**Screen recording:**

https://github.com/user-attachments/assets/4596838d-d81e-4942-8233-7b64d5266421

https://github.com/user-attachments/assets/7421c3fd-d55f-4cfb-838e-c278938fc9e5

**Comment by luisecm** [comment]
As a side note, if you manually create a folder and then subfolders on it, you can browse through them, so the problem is related to the chats media folder
