### ISSUE TITLE
improvement(Friending): Navigate to Active Requests on Notification

### ISSUE THREAD

**Issue by XileHorizon** [Satellite-im/UplinkWeb#608]
If a user clicks on the friend request notification body instead of the "x" it should navigate them to the active requests area so they can confirm or deny the request. Right now, no matter where you click on the notification, it just closes.
![image](https://github.com/user-attachments/assets/ce6b0ed0-a5f4-4270-9238-2b6aa6caf8f7)

**Comment by Jekrimo** [comment]
@phillsatellite I just test toasts for new message and new friend request and both toast went to the correct page, I think we can close for now but maybe see if @XileHorizon is still having the issue?
