### ISSUE TITLE
bug(Files): "Empty Name" toast notification when naming a folder

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/UplinkWeb#631]
**Issue:**
A toast notification appears when you create a folder with a valid name that says "Empty Name Provided"

If you attempt to create a folder without a name no toast notification appears

This toast notification should appear for when the user attempts to create a folder with a blank name rather than a valid name

**Screen recording:**

https://github.com/user-attachments/assets/f15d21a7-72c5-4036-a3cb-23e69234c81a

**Comment by luisecm** [comment]
Increased priority to medium since this one is pretty annoying and a very basic flow in the app
