### ISSUE TITLE
bug(desktop): ubuntu app freezes after entering pin on create account

### ISSUE THREAD

**Issue by luisecm** [Satellite-im/UplinkWeb#641]
1. Install Uplink app on Ubuntu (you can get it from any PR desktop build ci workflow artifact) or following the instructions in here https://tauri.app/v1/guides/building/linux
2. Open uplink app on Ubuntu
3. Click on Create Account and then enter a valid pin
4. After clicking on Confirm Pin button the app freezes (sometimes even after clicking on first button freezes)

[Screencast from 26-09-24 11:39:50.webm](https://github.com/user-attachments/assets/b93547dd-c524-45a5-963a-f1b82dd95dfc)

**Comment by luisecm** [comment]
So I did some research on my end and here are my findings:

- We migrated from tauri v1 to v2 expecting this would be the solution but this did not work on my side - even though in docs they say you should use tauri v2 for Ubuntu 24.04 (ubuntu-latest) and libwebkit2gtk4-1
- There is little or nothing documented about this, but I found that we are not alone on this - https://www.firezone.dev/blog/using-tauri there have been compatibility issues reported for debian packages
- One possible solution (might not be the best but the easier for now) should be to build for linux using electron? 

@dariusc93 I know you are way more experienced with Linux than me, so I am wondering if you know how could we solve this?

**Comment by tooshel** [comment]
@luisecm Is there any way to confirm the web browser it's using is chromium? Is Chromium installed on the target system? Does the config we use to build it bundle Chromium?

**Comment by luisecm** [comment]
@tooshel I do have chromium installed in the laptop I use to build on linux. Also the libraries listed by tauri as required to build in linux are installed too: 

`sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf`

source: https://tauri.app/es/distribute/pipelines/github/

Tested it locally and also using github actions. We already have a pipeline for building for Linux Ubuntu, and the .deb package and AppImage are successfully created, but after opening, you see the issue logged in here
