### ISSUE TITLE
bug(chat): Sometimes messages stop sending until refresh

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/UplinkWeb#654]
**Issue:**
Sometimes when you leave Uplink on idle for a couple minutes and then come back to it and try to send a message, the messages will not send until you refresh your browser page

*This doesnt happen every time 

**STR:**
- Leave Uplink sitting for about 2-3 minutes 
- Come back and try to send a message in chat
- Refresh webpage
- Send messages again

**Screen recording:**

https://github.com/user-attachments/assets/4a7b2367-c6cd-4b23-a864-7d94d38aa9e1

**Comment by Flemmli97** [comment]
does this still happen? i remember also having the websocket error which i thought might have something to do with it but i am now neither getting that error nor having message send problems anymore.

**Comment by stavares843** [comment]
yes phil and i saw this issue 2 days ago again

**Comment by phillsatellite** [comment]
Closing due to not being able to replicate again on Friday or Today. Were going to add messaging logs into dev so we can track this better and will re open the ticket if we come across it
