### ISSUE TITLE
task(Chats): Add count indicator for incoming messages

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/UplinkWeb#683]
**Issue:**
When the user gets a new message we should show an indicator that counts how many unread messages the user has. It should match the same style of the one we have for incoming friend requests 

<img width="104" alt="Screenshot 2024-10-07 at 4 34 55 PM" src="https://github.com/user-attachments/assets/e3fecb1e-0f47-45b5-8f2f-c3ec595ed55a">

**Comment by Flemmli97** [comment]
this is already in #685
