### ISSUE TITLE
bug(Calling): New call starts when going back to chat 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/UplinkWeb#688]
**Issue:**
If you are in a call and you nav to a different page and then back to that chat again it will start a new call 

**STR:**
Join call with User B
Go to Settings while still in call 
Go back to chat 
User B will get another incoming call from you 

**Screen recording:**

https://github.com/user-attachments/assets/9195b6d6-49c9-49d3-9649-42c2fe425dd8

**Comment by lgmarchi** [comment]
This problem is not happening anymore. I suggest to close it. 

@phillsatellite @tooshel @stavares843 @luisecm
