### ISSUE TITLE
Group Members - Checkbox next to username from list should work in the same way as the group members input

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/UplinkWeb#775]
The checkbox next to usernames in the group members list should be interactive like the group members input.

**Comment by Flemmli97** [comment]
<img width="686" alt="Screenshot 2024-10-31 at 17 09 36" src="https://github.com/user-attachments/assets/08627d9e-5188-48b6-bed2-4fd9a171ff3c">

do you mean this? cause for me i can click on it fine

**Comment by stavares843** [comment]
yes on that modal works fine

but in the In the Groups Members it does not, we have a issue for that here
https://github.com/Satellite-im/UplinkWeb/issues/764
