### ISSUE TITLE
Improve navigation on mobile using bottomNavBar

### ISSUE THREAD

**Issue by lgmarchi** [Satellite-im/UplinkWeb#907]

**Comment by phillsatellite** [comment]
@lgmarchi what does this ticket try to address in regards to the bottomNavBar? Is it related to this pr https://github.com/Satellite-im/UplinkWeb/pull/900 ? I am noticing some issues with the nav bar on mobile and don't want to create duplicate tickets

Let me know if either of these are what this ticket is trying to address https://github.com/Satellite-im/UplinkWeb/issues/910 https://github.com/Satellite-im/UplinkWeb/issues/909

**Comment by lgmarchi** [comment]
> @lgmarchi what does this ticket try to address in regards to the bottomNavBar? Is it related to this pr #900 ? I am noticing some issues with the nav bar on mobile and don't want to create duplicate tickets
> 
> Let me know if either of these are what this ticket is trying to address #910 #909

It is, yes. 

Issues were: 

1. When we go to settings, sidebar should be opened, and not profile page. 

2. When we go to chats, sidebar bar should be opened, and not the active chat
