### ISSUE TITLE
bug(iOS): App freezes momentarily when user taps chat

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/UplinkWeb#909]
**Issue:**
- When the user taps on the chat button on an iOS device it takes fairly long to load the page and when it is loading user cant tap anything else. Ive always noticed the option to paste text will appear when the user taps the chat button 

*This bug is specific to iOS it does not happen on Android devices*

**STR:**
- On an iOS device simply go to any page (except chats) and then go back to the chat page 

**Screen recording:**

https://github.com/user-attachments/assets/9d1e205a-3098-4226-9858-08b5bf91252b

**Comment by Flemmli97** [comment]
btw im getting this on mac too. havent tried other os though

**Comment by phillsatellite** [comment]
> btw im getting this on mac too. havent tried other os though

Weird Ive only gotten this on iOS. Couldnt replicate on macOS or Android
