### ISSUE TITLE
bug(mobile): navBar glitches when opening sidebar

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/UplinkWeb#910]
**Issue:**
- When you open the sidebar there is a glitch that flashes the stacked navBar for a moment 

**Devices:**
Android 
iOS

**STR:**
- Simply open the sidebar

**Screen recording:**

https://github.com/user-attachments/assets/87372a84-4d80-4928-95c5-74b8056f7845

https://github.com/user-attachments/assets/738021e6-06fe-4210-9c8d-122a6baed8be

**Comment by lgmarchi** [comment]
@phillsatellite is it happening yet?
