### ISSUE TITLE
Bug: Not getting friend request on mobile.

### ISSUE THREAD

**Issue by dillfrescott** [Satellite-im/UplinkWeb#914]
I'm sending the request from an account on windows desktop to my android phone on brave browser. and I'm never getting the friend request on my phone at all.

**Comment by stavares843** [comment]
Hi @dillfrescott ! 👋 

Thank you so much for your report!

Could you kindly confirm which version of the application you’re using? A screenshot would be helpful too! This is just to ensure you’re on the latest version. You can find this information by navigating to Settings > About.

For reference, here’s an example:
<img width="1331" alt="Example Screenshot" src="https://github.com/user-attachments/assets/2deb260f-aed4-4d72-ba3e-00cfe234aa62">

Thank you for your help!

Best regards,

**Comment by dillfrescott** [comment]
Sure! Sorry it took me so long I was a bit busy with stuff!

![Screenshot 2024-12-05 200112](https://github.com/user-attachments/assets/41fd3b67-b01e-486a-a4ca-99ec92785362)

**Comment by dillfrescott** [comment]
Yeah tested on Brave and chrome on my android phone and im not not getting any friend requests from my desktop account.

**Comment by dariusc93** [comment]
> Yeah tested on Brave and chrome on my android phone and im not not getting any friend requests from my desktop account.

Does the browser console report any errors?

**Comment by stavares843** [comment]
Hi @dillfrescott! 👋

Thank you for sharing the screenshot!

Could you also send us a screenshot of your Console tab while using [chat.satellite.im](https://chat.satellite.im/) on your Brave browser (desktop)? This will help us identify any potential errors.

Here’s how you can access this information:

- Right-click on the page and select Inspect.
- In the Developer Tools panel that opens, click the Console tab.

For reference:

Right-click > Inspect

<img width="1202" alt="Screenshot example showing how to inspect the browser page." src="https://github.com/user-attachments/assets/649aacea-6c80-478f-802b-37e611f67363">

Console tab view

<img width="716" alt="Screenshot example showing the console tab." src="https://github.com/user-attachments/assets/d65c10a9-c51c-4a29-ad08-6a4ec4c3c0a3">

Once you’ve opened the Console tab:

- Try to perform the action (e.g., sending a friend request) that’s causing the issue.
- Take a screenshot of any errors that appear in the Console tab and share it with us.

We appreciate your help in troubleshooting this!

Best regards,

**Comment by dillfrescott** [comment]
Ok so I updated Uplink Web and it must have just taken a bit for my browser cache to update the site because its working now!

But i cant start a call unless I have a webcam plugged in. Can you please fix that so you can start a voice call with just a microphone? I would truly appreciate it!

**Comment by dillfrescott** [comment]
And one other thing. On mobile you cant see the bottom nav bar because the bottom browser buttons get in the way. The only way around it is to save the page to your phone home screen to see the bottom nav bar.

**Comment by dillfrescott** [comment]
Actually I even plugged in a webcam and am still unable to connect to a call. i called with my phone and it just rings with no popup on my desktop. no console errors either.

**Comment by dillfrescott** [comment]
![image](https://github.com/user-attachments/assets/b4d13816-fd9b-4f1b-aa28-ae8df5786fa0)

**Comment by stavares843** [comment]
Thank you so much for sharing your feedback! We really appreciate it and will definitely look into these issues. Making things easier and more intuitive is super important to us.

If there’s anything else on your mind, don’t hesitate to let us know—we’re always here to listen!

In the meantime, we’ll keep you updated as we work on these fixes and improvements. Thanks again for helping us make things better!

**Comment by dillfrescott** [comment]
No problem! Thank you guys for making such a cool software!
