### ISSUE TITLE
bug(iOS): Email Us button only works on desktop 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/UplinkWeb#931]
**Issue:**
The _Email Us_ button only seems to work on desktop. When you tap it on a mobile device it does nothing

**Steps to reproduce:**
- Go to Settings / Profile 
- Scroll down to Email Us
- Tap the Email Us button

**Devices:**
Mobile 

**Screen recording:**
Mobile - 

https://github.com/user-attachments/assets/b1d0f05f-73b3-4c74-92a4-de9a05738871

Desktop - 

https://github.com/user-attachments/assets/053a6334-d291-44d1-b65e-5202ad59678a

**Comment by lgmarchi** [comment]
@phillsatellite Worked on my iOS.
