### ISSUE TITLE
bug(global): White screen before loading into app

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/UplinkWeb#940]
**Issue:**
- If you open a new tab and go to localhost it flashes a white screen for a split second and then loads into the app. 

- This is messing up the playwright tests, when a valid response is done in the browser, playwright thinks everything is then ready to test but it isn't due to the split second it shows the white screen

**Steps to reproduce:**
- Open a new tab 
- Go to Localhost

*To replicate this on iOS build the app and open it. Usually opening on the first time after building will show the bug

**Devices:**
- iOS
- Desktop

**Screen recording:**

https://github.com/user-attachments/assets/2345cf5c-8536-4b19-85be-ede24905a7a2

https://github.com/user-attachments/assets/a09b1896-24c0-493b-bbcb-94fbb14771ab

**Comment by stavares843** [comment]
closing this since a flash for a white screen for a split second and then loads into the app is not a priority atm and this is a very very old bug
